[project]
name = "cu-sci-studio-bot"
version = "0.1.0"
description = "Survey in telegram bot"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "aiogram>=3.22.0",
    "asyncio>=4.0.0",
    "dotenv>=0.9.9",
    "pydantic>=2.11.10",
    "pymongo>=4.15.4",
    "qrcode[pil]>=8.2",
]
